---
- name: My first play
  hosts: all
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:

  - name: Create wordpress Volume
    become: yes
    community.docker.docker_volume:
      name: wordpress_vol

  - name: Create new network
    become: yes
    community.docker.docker_network:
      name: inception_network

  - name: Copy files to the remote machine
    become: yes
    become_method: sudo
    copy:
      src: /Users/aybouras/Desktop/ansible_docker/inception
      dest: /home
      mode: preserve
  
  - name: build Docker image from the nginx local Dockerfile
    become: yes
    become_method: sudo
    community.docker.docker_image:
      name: nginx
      source: build
      build:
        path: /home/inception/nginx
      state: present

  - name: run nginx container
    become: yes
    community.docker.docker_container:
      image: nginx
      name: nginx
      ports:
        - "8080:8080"
        - "443:443"
      networks:
        - name: inception_network
      restart_policy: always
      state: started
      env_file: /home/inception/.env
      volumes:
        - wordpress_vol:/var/www/wordpress

  - name: build Docker image from the wordpress Dockerfile
    become: yes
    become_method: sudo
    community.docker.docker_image:
      name: wordpress
      source: build
      build:
        path: /home/inception/wordpress
      state: present

  - name: run wordpress container
    become: yes
    community.docker.docker_container:
      image: wordpress
      name: wordpress
      ports:
        - "9000:9000"
      networks:
        - name: inception_network
      restart_policy: always
      state: started
      env_file: /home/inception/.env
      volumes:
        - wordpress_vol:/var/www/wordpress